filter:
    excluded_paths:
        - 'js/vendor/*'
        - 'js/public/*'
        - 'l10n/*'


imports:
    - javascript
    - php

build:
    tests:
        override:
            -  jshint-run --config js/.jshintrc
