filter:
      excluded_paths:
        - 'l10n/*'
        - 'js/vendor/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage: false

build:
    environment:
        php: 7.4.13
    tests:
        override:
          -  jshint-run --config .jshintrc
