filter:
      excluded_paths:
        - 'l10n/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage: false

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
