filter:
    excluded_paths:
        - 'l10n/*'
        - 'jquery.datetimepicker.full.min.js'


imports:
    - javascript
    - php

build:
    tests:
        override:
            -  jshint-run --config js/.jshintrc
