filter:
  excluded_paths:
    - 'l10n/*'
    - 'js/vendor/*'

imports:
  - javascript
  - php

tools:
  external_code_coverage:
    timeout: 1000

build:
  tests:
    override:
      -  jshint-run --config js/.jshintrc

coding_style:
  php:
    indentation:
      general:
        use_tabs: true
        size: 4
      switch:
        indent_case: true
    spaces:
      general:
        linefeed_character: newline
      within:
        brackets: false
