filter:
    excluded_paths:
        - 'js/vendor/*'
        - 'js/public/*'
        - 'l10n/*'


imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 1000

build:
    tests:
        override:
            -  jshint-run --config js/.jshintrc
