filter:
      excluded_paths:
        - 'l10n/*'
        - 'js/vendor/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage: false

build:
    tests:
        override:
          -  jshint-run --config .jshintrc
    environment:
        node: v12.16.3
        php:
            version: "7.4"
