sudo: required
dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  global:
    - CORE_BRANCH=stable12
  matrix:
    - DB=mysql
    - DB=sqlite
    - DB=pgsql

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh polls $CORE_BRANCH $DB
  - cd ../server
  - ./occ app:enable polls

before_script:
  - cd apps/polls

script:
  - make test

after_failure:
  - cat ../../data/nextcloud.log
